### ISSUE TITLE
Can't Install with Electron (Mac Big Sur). Error: Cannot find module "node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs"

### ISSUE THREAD

**Issue by NL33** [nut-tree/nut.js#221]
**Version**
@nut-tree/nut-js: 1.6.0
electron: 12.0.2
electron-rebuild: 2.3.5
node-gyp: 8.0.0
opencv4nodejs: 5.6.0
Mac OS: 11.1

**Short overview**
I am trying to get nut.js to work with electron (my machine: Mac, OS 11.1). I have gone through the installation steps, but when I go to start the app, I continually get the error: 
`Cannot find module "node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs"`. 

If I try to run `$ npm run rebuild`, I get the error: 
```
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/.../node_modules/opencv4nodejs'.
Error: `make` failed with exit code: 2
```
**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [X] Dev/Host system

**Detailed error description**

I have gone through the installation steps for Electron and Mac. Including (in my electron app):
`$ npm i @nut-tree/nut-js`
`$ npm i -D electron-rebuild`

And then attempted to run 
`$ npm i electron-rebuild`

but got error:
```
Error: node-gyp failed to rebuild '/.../node_modules/opencv4nodejs'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/.../node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I then installed additional items:
```
$ xcode-select --install

$ npm install opencv4nodejs

$ npm install node-gyp
```
All installed without error. But even after these steps, I still get the node gyp error above whenever I run `$ npm run rebuild`.

And if I try $ `npm start ` I get the error:

```
App threw an error during load
Error: Cannot find module '/.../node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs'

```
**Steps to reproduce error**
See above description of steps I've taken.

**Additional content**

N/A

**Comment by s1hofmann** [comment]
Hi @NL33 👋 

version 1.6.0 of `nut.js` is not compatible with Electron version > 8.x (see https://github.com/nut-tree/nut.js/issues/166).

The `@next` snapshot already supports all recent Electron versions, but be aware that these are development releases:

`npm i @nut-tree/nut-js@next`

**Comment by NL33** [comment]
Thanks very much @s1hofmann. After installing nut-js@next, I get this error when trying $ npm start:

```
App threw an error during load
Error: The module '/.../node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I'm not really familiar with `opencv4nodejs`, but it must be some kind of very large module, no? When I had tried to install it with $ npm i opencv4nodejs, the installation took about 30 minutes (most packages take 30 seconds).

After getting the error above, I tried running `$ npm rebuild`, and it began another huge 30 minute process.

An hour of installations seems like overkill for me to test out the @next package. Am I missing something, or is this to be expected?

**Comment by svettwer** [comment]
Nut.js comes with prebuilds of opencv to prevent the user from performing that 30 minutes build whenever an installation is done. For me it looks like the pre built does not match your node version.

**Comment by s1hofmann** [comment]
Hi @NL33 👋 

I ran a small sample using Electron 12 with `@nut-tree/nut-js@next` on my Big Sur machine and can confirm it works as expected and the installation process went quite fast and smoothly.

Did you follow the [Electron usage guide](https://github.com/nut-tree/nut.js#usage-with-electron)?

Given your description of a 30 minutes installation process I'm assuming some things, please correct me if I'm wrong:

- You're running node 13 on your machine
- On `install` it re-compiled `opencv4nodejs` for node 13, since there are no prebuilds for this version available (according to NODE_MODULE_VERSION 79)
- You did not run a custom `rebuild` script via `npm run rebuild` as shown in [the nut.js readme](https://github.com/nut-tree/nut.js#usage-with-electron) but `npm rebuild`, otherwise it should download prebuilds for your Electron version (according to the required NODE_MODULE_VERSION 87)


## Additional infos, skip if not interested

--- 

## I'm not familiar with native node addons, could you explain a bit?

`opencv4nodejs-prebuilt` provides node bindings for OpenCV via [native abstractions for node](https://nodejs.org/api/addons.html#addons_native_abstractions_for_node_js) (a.k.a. `nan`).

The problem with `nan` based bindings is the fact that they rely on a specific application binary interface (ABI), since they are directly calling e.g. V8 functions. Unfortunately, this ABI is not stable across multiple node versions, so we need to compile our native addon for each version of node we want to use it with.
These ABI versions are referred to as `NODE_MODULE_VERSION` and [this list of node releases](https://nodejs.org/en/download/releases/) shows which node versions uses which ABI.

Since Electron is not exactly node, it comes with a slightly different ABI, so in order to use a `nan` module with Electron, we have to build it for the specific ABI.
An easy way to check the ABI version of your Electron version in use is to run `npx electron --abi` in your project.

## Ok, so how does this work in `nut.js`?

`nut.js` or more specifically `opencv4nodejs-prebuilt` provides prebuilt bindings for all current LTS versions of node as well as several version of Electron.

You can verify this on the [latest release of opencv4nodejs-prebuilt](https://github.com/nut-tree/opencv4nodejs/releases/tag/v5.3.1).
There are several assets storing precompiled addons for multiple node / Electron versions for Windows / Linux / macOS.

`opencv4nodejs-prebuilt-v5.3.1-electron-v87-darwin-x64.tar.gz` would be the correct prebuild for Electron v12 on macOS.
`electron-rebuild` would download this archive from the GitHub release and extract it to your project, skipping a recompilation.

**Comment by NL33** [comment]
Thanks for your follow-up. It's very helpful. 

Yes I am currently running node v 13.0.1.

I reverted the app to prior to going through the nut.js installation. So now the app is back to where it was prior. 

I thought I'd try to go through the electron install again, so I just ran:

`$ npm i @nut-tree/nut-js@next`

And I got these errors:
```
npm ERR! code 1
npm ERR! path /.../node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform darwin
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=13.0.1 runtime=node arch=x64 libc= platform=darwin)
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-darwin@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /.../.npm/_logs/2021-04-15T...-debug.log
npm ERR! child_process.js:642
npm ERR!     throw err;
```

Do you recommend I do something different?

**Comment by s1hofmann** [comment]
Hi @NL33 👋 

The *fastest* thing you could do (if feasible for you) would be to switch to an LTS version of node (12 or 14) or the current latest version (15).
For these versions `nut.js` provides prebuilt node bindings so you don't have to compile them yourself on `install`.
Once installed, run the `electron-rebuild` step as [described in the readme](https://github.com/nut-tree/nut.js#usage-with-electron).

If you can't switch to a different node version you'd have to run the compilation once on install, but the `electron-rebuild` step will work just as fine. (Just tried it on my machine)

**Comment by NL33** [comment]
It worked! 

I just went ahead and upgraded Node to latest stable (node v 14.6.1). 

Then, per your info:
`$ npm i @nut-tree/nut-js@next`
`$ npm i -D electron-rebuild`

package.json:

```
...
"scripts": {
    "rebuild": "electron-rebuild
}
...
```

`$ npm run rebuild`

And from there no errors and I'm able to require nutjs in the app.

Thanks again.

**Comment by s1hofmann** [comment]
You're welcome 👍

**Comment by peec** [comment]
I stumbeled upon this issue for some days ago, i had to run 

`electron-rebuild -f -t prod,optional,dev` for it to correctly build ( default -t does not include "dev").

```
...
"scripts": {
    "rebuild": "electron-rebuild -f -t prod,optional,dev"
}
...
```
